### PR TITLE
Ability to work with 5sim.net 

### PR DESCRIPTION
**Pull request by maxim-smirnov**

### CODE REVIEW

**Comment by owneroxxor** [comment]
is this 5sim integration working already?

**Comment by maxim-smirnov** [comment]
It was working on commit date, did not checked now. But all services with sms-activate like API should work.

**Comment by sla-te** [comment]
plz integrate 5sim.net

**Comment by KuroSol** [comment]
File "custom.py", line 9, in <module>
    wrapper = Sms('API KEY', 'http://sms-activate.api.5sim.net/stubs/handler_api.php')
TypeError: __init__() takes 2 positional arguments but 3 were given

**Comment by PoseidonFury** [comment]
Did you manage to fix this and could you post it on you're GitHub >  File "custom.py", line 9, in <module>
> 
>     wrapper = Sms('API KEY', 'http://sms-activate.api.5sim.net/stubs/handler_api.php')
> 
> TypeError: __init__() takes 2 positional arguments but 3 were given
> 
>

**Comment by PoseidonFury** [comment]
Traceback (most recent call last):
  File "C:\Users\Melisande\Desktop\python-sms-activate-ru-master\example\custom.py", line 12, in <module>
    balance = GetBalance().request(wrapper)
  File "C:\Users\Melisande\Desktop\python-sms-activate-ru-master\example\smsactivateru\actions.py", line 26, in request
    return self.__response_processing(response)
  File "C:\Users\Melisande\Desktop\python-sms-activate-ru-master\example\smsactivateru\errors.py", line 63, in wrapper
    raise except_class(message=ErrorStorage.codes[key]['text'], code=key)
smsactivateru.helper.InvalidApiKey: ('Неверный API ключ доступа', 'BAD_KEY')

**Comment by Andromeda606** [comment]
What is the situation?

**Pull request closed without merging**
